### ISSUE TITLE
Redirect link

### ISSUE THREAD

**Issue by don-vip** [Flacus/Windrad#1]
https://github.com/Flacus/Windrad/blob/master/windrad.xml has redirect link, can you please fix it?

Found HTTP redirection for http://wiki.openstreetmap.org/wiki/DE:Tag:generator:source=wind -> 301 -> https://wiki.openstreetmap.org/wiki/DE:Tag:generator:source=wind

See https://josm.openstreetmap.de/ticket/17240

**Comment by Klumbumbus** [comment]
I moved the preset to https://josm.openstreetmap.de/wiki/Presets/Windrad and fixed it there.

**Comment by don-vip** [comment]
Thanks!
